---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maktum
spec:
  selector:
    matchLabels:
      app: maktum
  replicas: 1
  template:
    metadata:
      labels:
        app: maktum
    spec:
      containers:
      - name: mycontainerad
        image: maktumsab/java-app:6
        imagePullPolicy: IfNotPresent

---


apiVersion: v1
kind: Service
metadata:
  name: maktum
spec:
  type: LoadBalancer
  ports:
  - port: 8082
  selector:
    app: maktum

